# Generated by Django 3.2 on 2021-10-20 04:41

import ckeditor.fields
import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Employee_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('doors', models.CharField(choices=[('Blood, Heart and Circulation', 'Blood, Heart and Circulation'), ('Bones, Joints and Muscles', 'Bones, Joints and Muscles'), ('Brain and Nerves', 'Brain and Nerves'), ('Digestive System', 'Digestive System'), ('Ear, Nose and Throat', 'Ear, Nose and Throat'), ('Endocrine System', 'Endocrine System'), ('Immune System', 'Immune System'), ('Kidneys and Urinary System', 'Kidneys and Urinary System'), ('Lungs and Breathing', 'Lungs and Breathing'), ('Mouth and Teeth', 'Mouth and Teeth')], max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
