# Generated by Django 3.2 on 2021-10-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Employee_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
    ]
