# Generated by Django 3.2.8 on 2021-10-20 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_auto_20211020_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ticketapp.contact')),
                ('status', models.CharField(choices=[('process', 'process'), ('activate', 'activate')], max_length=10)),
            ],
        ),
    ]
